### ISSUE TITLE
Yandexmusic library is empty

### ISSUE THREAD

**Issue by evgley** [IrokezPetrovic/mopidy-yandexmusic#2]
Hi! I've tried to use this extension with Mopidy 3.0.2 and python  3.7.3 on Raspbian buster.

Seems like it can only load playlists, but there is no way to browse yandexmusic.
When I press "Browse" there is a button "root" which is related to mopidy-yandexmusic.
Just after pressing the button I can see blank list and the following error in log:

```
DEBUG    [HttpServer] mopidy.http.handlers Received WebSocket message from 192.168.1.45: '{"method":"core.library.lookup","params":{"uris":["yandexmusic:directory:root"]},"jsonrpc":"2.0","id":90}'
ERROR    [Core-7] mopidy.core.library YandexMusicBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 217, in lookup
    result = future.get()
  File "/usr/local/lib/python3.7/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python3.7/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_yandexmusic/library_provider.py", line 21, in lookup
    _, kind, ymartist_id, ymtrack_id = uri.split(":")
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by IrokezPetrovic** [comment]
Library browsing not implemented yet :(
